# Generated by Django 6.1.1 on 2026-10-04 13:13

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("html", "HTML"),
                            ("docx", "Word"),
                            ("xlsx", "Excel"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("ready", "Ready"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("storage_key", models.CharField(blank=True, max_length=512)),
                ("config", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.organization",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reports",
                        to="workspaces.project",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
                "indexes": [
                    models.Index(
                        fields=["organization", "project", "created_at"],
                        name="ix_report_org_proj_ts",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("format__in", ["pdf", "html", "docx", "xlsx"])
                        ),
                        name="ck_report_format",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("status__in", ["pending", "ready", "failed"])
                        ),
                        name="ck_report_status",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("status", "ready"), _negated=True),
                            models.Q(("storage_key", ""), _negated=True),
                            _connector="OR",
                        ),
                        name="ck_report_ready_has_key",
                    ),
                ],
            },
        ),
    ]
