# Generated by Django 6.1.1 on 2026-10-04 13:13

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
        ),
        migrations.CreateModel(
            name="DatasetRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "source_format",
                    models.CharField(
                        choices=[
                            ("csv", "CSV"),
                            ("json", "JSON"),
                            ("txt", "Text"),
                            ("xlsx", "Excel (.xlsx)"),
                            ("xls", "Excel (.xls)"),
                            ("sqlite", "SQLite"),
                            ("pdf", "PDF"),
                            ("docx", "Word"),
                            ("xml", "XML"),
                            ("image_ocr", "Image (OCR)"),
                            ("ods", "OpenDocument spreadsheet"),
                            ("yaml", "YAML"),
                            ("parquet", "Parquet"),
                            ("feather", "Feather"),
                            ("pptx", "PowerPoint"),
                            ("html", "HTML"),
                        ],
                        max_length=32,
                    ),
                ),
                ("parent_dataset_id", models.UUIDField(blank=True, null=True)),
                ("storage_key", models.CharField(max_length=512)),
                ("row_count", models.PositiveBigIntegerField()),
                ("column_count", models.PositiveBigIntegerField()),
                ("derivation_description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.organization",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="datasets",
                        to="workspaces.project",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
        ),
        migrations.CreateModel(
            name="Dashboard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("layout", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.organization",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dashboards",
                        to="workspaces.project",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
        ),
        migrations.CreateModel(
            name="ChartSpec",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "chart_type",
                    models.CharField(
                        choices=[
                            ("bar", "Bar"),
                            ("pie", "Pie"),
                            ("line", "Line"),
                            ("scatter", "Scatter"),
                            ("histogram", "Histogram"),
                            ("box_plot", "Box plot"),
                            ("heatmap", "Heatmap"),
                            ("bubble", "Bubble"),
                            ("treemap", "Treemap"),
                            ("radar", "Radar"),
                            ("waterfall", "Waterfall"),
                            ("funnel", "Funnel"),
                        ],
                        max_length=32,
                    ),
                ),
                ("spec", models.JSONField(blank=True, default=dict)),
                ("title", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.organization",
                    ),
                ),
                (
                    "dataset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chart_specs",
                        to="workspaces.datasetrecord",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chart_specs",
                        to="workspaces.project",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["organization", "created_at"], name="ix_project_org_ts"
            ),
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.UniqueConstraint(
                fields=("organization", "name"), name="uq_project_org_name"
            ),
        ),
        migrations.AddIndex(
            model_name="datasetrecord",
            index=models.Index(
                fields=["organization", "project", "created_at"],
                name="ix_dataset_org_proj_ts",
            ),
        ),
        migrations.AddIndex(
            model_name="datasetrecord",
            index=models.Index(
                fields=["organization", "parent_dataset_id"],
                name="ix_dataset_org_parent",
            ),
        ),
        migrations.AddConstraint(
            model_name="datasetrecord",
            constraint=models.CheckConstraint(
                condition=models.Q(("row_count__gte", 0)), name="ck_dataset_rows_nonneg"
            ),
        ),
        migrations.AddConstraint(
            model_name="datasetrecord",
            constraint=models.CheckConstraint(
                condition=models.Q(("column_count__gte", 0)),
                name="ck_dataset_cols_nonneg",
            ),
        ),
        migrations.AddConstraint(
            model_name="datasetrecord",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("parent_dataset_id", models.F("id")), _negated=True
                ),
                name="ck_dataset_not_own_parent",
            ),
        ),
        migrations.AddIndex(
            model_name="dashboard",
            index=models.Index(
                fields=["organization", "project", "created_at"],
                name="ix_dash_org_proj_ts",
            ),
        ),
        migrations.AddIndex(
            model_name="chartspec",
            index=models.Index(
                fields=["organization", "project", "created_at"],
                name="ix_chart_org_proj_ts",
            ),
        ),
    ]
