# Generated by Django 6.1.1 on 2026-10-04 13:13

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PipelineNode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("dataset", "Dataset"), ("artifact", "Artifact")],
                        max_length=16,
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dataset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pipeline_nodes",
                        to="workspaces.datasetrecord",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.organization",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pipeline_nodes",
                        to="workspaces.project",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
        ),
        migrations.CreateModel(
            name="PipelineEdge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("transform", "Transform")], max_length=16
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.organization",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pipeline_edges",
                        to="workspaces.project",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_edges",
                        to="pipeline.pipelinenode",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_edges",
                        to="pipeline.pipelinenode",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("version", models.PositiveIntegerField(default=1)),
                ("definition", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.organization",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipes",
                        to="workspaces.project",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
        ),
        migrations.AddIndex(
            model_name="pipelinenode",
            index=models.Index(
                fields=["organization", "project", "created_at"],
                name="ix_node_org_proj_ts",
            ),
        ),
        migrations.AddConstraint(
            model_name="pipelinenode",
            constraint=models.CheckConstraint(
                condition=models.Q(("kind__in", ["dataset", "artifact"])),
                name="ck_node_kind",
            ),
        ),
        migrations.AddIndex(
            model_name="pipelineedge",
            index=models.Index(
                fields=["organization", "project"], name="ix_edge_org_proj"
            ),
        ),
        migrations.AddConstraint(
            model_name="pipelineedge",
            constraint=models.UniqueConstraint(
                fields=("source", "target", "kind"), name="uq_edge_src_tgt_kind"
            ),
        ),
        migrations.AddConstraint(
            model_name="pipelineedge",
            constraint=models.CheckConstraint(
                condition=models.Q(("source", models.F("target")), _negated=True),
                name="ck_edge_no_self_loop",
            ),
        ),
        migrations.AddConstraint(
            model_name="pipelineedge",
            constraint=models.CheckConstraint(
                condition=models.Q(("kind__in", ["transform"])), name="ck_edge_kind"
            ),
        ),
        migrations.AddIndex(
            model_name="recipe",
            index=models.Index(
                fields=["organization", "project", "created_at"],
                name="ix_recipe_org_proj_ts",
            ),
        ),
        migrations.AddConstraint(
            model_name="recipe",
            constraint=models.UniqueConstraint(
                fields=("project", "name", "version"), name="uq_recipe_project_name_ver"
            ),
        ),
        migrations.AddConstraint(
            model_name="recipe",
            constraint=models.CheckConstraint(
                condition=models.Q(("version__gte", 1)), name="ck_recipe_version_pos"
            ),
        ),
    ]
